name: rust-postgres

services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    env_file:
      - ../.env

  db:
    image: "postgres:16"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres-data:
